import pydirectinput
delaytime = 0
pydirectinput.press('`',interval=0.0)
# time.sleep(delaytime)
pydirectinput.press('5',interval=0.0)
# time.sleep(delaytime)
pydirectinput.press('h',interval=0.0)
# time.sleep(delaytime)        
pydirectinput.press('2',interval=0.0)
# time.sleep(delaytime)
pydirectinput.press('r',interval=0.0)
# time.sleep(delaytime)
pydirectinput.press('3',interval=0.0)
# time.sleep(delaytime)
pydirectinput.press('r',interval=0.0)
# time.sleep(delaytime)
pydirectinput.press('1',interval=0.0)
# time.sleep(delaytime)
# pydirectinput.keyDown('ctrl')
pydirectinput.press('g')
# time.sleep(delaytime)
pydirectinput.press('t')   
# pydirectinput.keyUp('ctrl')
# time.sleep(delaytime)  

# import pyautogui
# delaytime = 0
# pyautogui.press('`',interval=0.0)
# # time.sleep(delaytime)
# pyautogui.press('5',interval=0.0)
# # time.sleep(delaytime)
# pyautogui.press('h',interval=0.0)
# # time.sleep(delaytime)        
# pyautogui.press('2',interval=0.0)
# # time.sleep(delaytime)
# pyautogui.press('r',interval=0.0)
# # time.sleep(delaytime)
# pyautogui.press('3',interval=0.0)
# # time.sleep(delaytime)
# pyautogui.press('r',interval=0.0)
# # time.sleep(delaytime)
# pyautogui.press('1',interval=0.0)
# # time.sleep(delaytime)
# # pyautogui.keyDown('ctrl')
# pyautogui.press('g')
# # time.sleep(delaytime)
# pyautogui.press('t')   
# # pyautogui.keyUp('ctrl')
# # time.sleep(delaytime)  